### ISSUE TITLE
[BUG] improper behavior of group function when one of arguments is empty serieslist

### ISSUE THREAD

**Issue by tantra35** [go-graphite/carbonapi#589] opened 2021-03-25 12:50 UTC
**Describe the bug**
If we write follow expression

```
group(some.existing.metrics, some.metrics.notexisten)
```

in such situations group returns nothing, but in graphiteweb it returns `some.existing.metrics`

**CarbonAPI Version**
0.15.6

**Logs**
No any errors in logs

**Comment by Civil** [comment] 2021-03-29 23:57
I can't reproduce that behavior. Config file might be useful to find out cause of that problem.

**Comment by tantra35** [comment] 2021-03-30 00:21
Seems that is reproduce only with wildcards:

for example:

```
group(app.*.http.totalrequest, app.*.http.totalrequest12)
```

Here `app.*.http.totalrequest` existen metrics, `app.*.http.totalrequest12` not exist

**Comment by Civil** [comment] 2021-03-30 08:06
Can you check if with that PR applied it is still reproducible?

https://github.com/go-graphite/carbonapi/pull/591

**Comment by Civil** [comment] 2021-03-30 12:18
That PR was just merged to the main branch. Could you try it and check if it works better now?

**Comment by tantra35** [comment] 2021-03-30 12:19
@Civil Just checked! Now all works as expected. Thanks

**Closed** 2021-03-30 12:23 UTC
Labels: bug
