### ISSUE TITLE
aggregateSeries panics on differing series lengths

### ISSUE THREAD

**Issue by arodland** [go-graphite/carbonapi#215] opened 2017-05-11 19:44 UTC
(Meta-issue: #161).

When passing series with different lengths to functions that use `aggregateSeries` (`sumSeries`, `avgSeries`, etc. including `groupByNode` on these things), not only is it not handled properly, we actually get a (recovered) panic.

Failing query (from error logs):

    removeEmptySeries(groupByNode(scaleToSeconds(statsite.counts.{skyfire,akfire,l3fire,l3l3fire}.lb.chopshop*.ext_status.*.[1-5]*, 1), 6, 'sum'))

[Stack trace](https://github.com/go-graphite/carbonapi/files/994225/stack.txt) (carbonapi is aa9a8a654a2c8db6add1c18fb74b320a9cd18f73).

**Comment by Dieterbe** [comment] 2017-05-11 19:47
shouldn't series be assured to have the same length before being passed into processing functions (e.g. right after fetching)?

**Comment by blysik** [comment] 2017-05-30 23:17
I'm seeing this error also. (Using sumSeries)

**Comment by Civil** [comment] 2017-06-08 14:18
I think that's a duplicate of https://github.com/go-graphite/carbonapi/issues/161

**Comment by maggnus** [comment] 2018-01-05 09:31
Aggregation functions doesn't work when gaps in data series exists.

`Jan  5 09:24:42 carbonapi: 2018-01-05T09:24:42.099Z#011ERROR#011render#011panic during eval:#011{"cache_key": "format=json&from=-30d&maxDataPoints=1622&target=maxSeries%28XXXXX%29&until=now", "stack": "main.renderHandler.func3.1\n\t/root/go/src/github.com/go-graphite/carbonapi/main.go:522\nruntime.call32\n\t/usr/local/go/src/runtime/asm_amd64.s:514\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:489\nruntime.panicindex\n\t/usr/local/go/src/runtime/panic.go:28\ngithub.com/go-graphite/carbonapi/expr.aggregateSeries\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:4140\ngithub.com/go-graphite/carbonapi/expr.EvalExpr\n\t/root/go/src/github.com/go-graphite/carbonapi/expr/expr.go:2206\nmain.renderHandler.func3\n\t/root/go/src/github.com/go-graphite/carbonapi/main.go:526\nmain.renderHandler\n\t/root/go/src/github.com/go-graphite/carbonapi/main.go:534\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2238\ngithub.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\ngithub.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:128\ngithub.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.ProxyHeaders.func1\n\t/root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1942\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2568\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1825"}`

**Comment by joemiller** [comment] 2018-03-20 16:37
We are starting to run into this issue more frequently as time goes by and we collect various little blips and gaps in our series. I'd like to help try to resolve it if possible. Is there any work in progress or tips toward a possible solution that I could look at to come up to speed?

**Comment by Civil** [comment] 2022-12-06 00:23
As far as I understand that should no longer happen in current master and actually since approx. 0.15.4 or so. If that is still a problem, please reopen.

**Closed by Civil** 2022-12-06 00:23 UTC
Labels: bug, graphite-web compatibility
