### ISSUE TITLE
color function does not work

### ISSUE THREAD

**Issue by lindsaylandry** [go-graphite/carbonapi#324] opened 2018-06-05 14:18 UTC
Any time i try to render a graph with the color function, i get no data. Not wrapping the query in a color returns data just fine.

Example: `&target=color(collectd.hostname.cpu.0.user, 'green')` will return no data

carbonapi version: 0.10.0.1
go-carbon version: 0.12.0

**Comment by azhiltsov** [comment] 2018-06-05 16:22
can you check pre cc11a89ed2ba9133e5cb52da3289c67f5c2a13d5 and see does it work?
I cant reproduce it, but we are running somewhat 13ebf4af4b68a2d4ecba27d0936e317883623fcc

**Comment by Civil** [comment] 2018-07-02 21:35
There is indeed something wrong with all png/svg related functions (color, etc). I've found one issue, but there is still something else.

**Comment by Civil** [comment] 2019-06-29 21:56
This issue likely is fixed in current version (0.12.0).

Please reopen if it still happens.

**Closed by Civil** 2019-06-29 21:56 UTC
