### ISSUE TITLE
Panic in response

### ISSUE THREAD

**Issue by proffust** [go-graphite/carbonapi#387] opened 2019-03-25 15:35 UTC
During a query with dots in tag values with multiple tags, I get a panic in the response. With the same query but without dots in tag values, the answer is correct.
Log failed request
https://pastebin.com/SLY2mfWX
Log success request
https://pastebin.com/g5BuTTta

**Comment by proffust** [comment] 2019-05-30 12:34
any updates?

**Comment by Civil** [comment] 2019-05-30 21:07
So far can't reproduce with current master.

**Comment by Civil** [comment] 2019-06-04 19:48
Should be fixed by:
https://github.com/go-graphite/carbonapi/commit/5a4fa2112923dd4c5d1a07164809a9da40dc0524

**Closed by Civil** 2019-06-04 19:48 UTC
