### ISSUE TITLE
[BUG] sortby functions doesn't seem to be returning right responses

### ISSUE THREAD

**Issue by ervikrant06** [go-graphite/carbonapi#586] opened 2021-03-22 08:47 UTC
**Describe the bug**

API call working with production graphite but not with graphite-clickhouse stack https://github.com/lomik/graphite-clickhouse
Also sortBy based API calls returning wrong results. 

**CarbonAPI Version**
carbonapi:0.14.2.1
graphite-clickhouse version: 0.12.0
vanila graphite: 1.1.4 

**Logs**
If applicable, add logs (please use log level debug) that shows the whole duration of the request. Request can be identified by UUID if needed.

**CarbonAPI Configuration:**
~~~
listen: "0.0.0.0:8081"
concurency: 1000
graphite:
    # Host:port where to send internal metrics
    # Empty = disabled
    host: "carbon-clickhouse-svc.ns-vaggarwal.svc.cluster.local:2003"
    interval: "60s"
    prefix: "carbon.api"
    # rules on how to construct metric name. For now only {prefix} and {fqdn} is supported.
    # {prefix} will be replaced with the content of {prefix}
    # {fqdn} will be repalced with fqdn
    pattern: "{prefix}.{fqdn}"

cache:
   # Type of caching. Valid: "mem", "memcache", "none"
   type: "mem"
   # Cache limit in megabytes
   size_mb: 0
   # Default cache timeout value. Identical to DEFAULT_CACHE_DURATION in graphite-web.
   defaultTimeoutSec: 60
upstreams:
  backendsv2:
    backends:
      -
        protocol: "carbonapi_v3_pb"
        lbMethod: "broadcast"
        maxBatchSize: 0
        servers:
          - "http://graphite-clickhouse-svc:9090"
~~~

Example query working with vanilla graphite stack but not with graphite-clickhouse stack. 

~~~
# curl "http://<VANILLA GRAPHITE>/render/?target=limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)&format=json&from=-5mins"
~~~

but same query failes with graphite-clickhouse stack with following error 

~~~
# curl "http://<GRAPHITE CLICKHOUSE>/render/?target=limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)&format=json&from=
-5mins"
Bad Request: Bad Request

Target              : limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)
Parsed so far       : limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5)
Could not parse     : ,4)
~~~

error fron log file 

~~~
2021-03-22T08:43:55.655Z        ERROR   access  request failed  {"data": {"handler":"render","carbonapi_uuid":"818d6c0c-7931-47ec-8940-c9ee2c823d98","url":"/render/?target=limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)&format=json&from=-5mins","peer_ip":"172.16.18.1","peer_port":"7670","host":"<GRAPHITE CLICKHOUSE>","format":"json","use_cache":true,"targets":["limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)"],"cache_timeout":60,"runtime":0.000056421,"http_code":400,"reason":"Bad Request\n\nTarget              : limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)\nParsed so far       : limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5)\nCould not parse     : ,4)\n","from":1616402335,"until":1616402635,"from_raw":"-5mins","uri":"/render/?target=limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)&format=json&from=-5mins","from_cache":false,"used_backend_cache":false,"request_headers":{}}}
~~~

--->  Also maxima function doesn't seems to be working as expected 

~~~
# curl "http://<clickhouse>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.read.bytes_out,1),'last',true),1),4)&format=json&from=-5mins" | python -m json.tool ; curl "http://<production graphite>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.read.bytes_out,1),'last',true),1),4)&format=json&from=-5mins" | python -m json.too
l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0   5034      0 --:--:-- --:--:-- --:--:--  5100
[
    {
        "datapoints": [
            [
                1574448,
                1616398980
            ],
            [
                1574448,
                1616399040
            ],
            [
                null,
                1616399100
            ],
            [
                null,
                1616399160
            ],
            [
                null,
                1616399220
            ]
        ],
        "tags": {
            "name": "test1"
        },

        },
        "target": "test1"
    }
]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   264  100   264    0     0   1236      0 --:--:-- --:--:-- --:--:--  1239
[
    {
        "datapoints": [
            [
                20188524544.0,
                1616398980
            ],
            [
                16447735808.0,
                1616399040
            ],
            [
                18457133056.0,
                1616399100
            ],
            [
                17974085632.0,
                1616399160
            ],
            [
                18284218368.0,
                1616399220
            ]
        ],
        "tags": {
            "name": "isilon.prod.isilon1.userstats.test100.read.bytes_out"
        },
        "target": "test100"
    }
]
~~~

cc: @Civil

**Comment by Felixoid** [comment] 2021-03-22 09:08
Have you seen an uneven amount of opening and closing parenthesis? `(()),4)`

`limit(sortByMaxima(isilon.prod.isilon1.userstats.*.read.bytes_out),5),4)`

I didn't look into the code yet, that's the first issue with the request I've recignized

**Comment by ervikrant06** [comment] 2021-03-22 09:38
yes you are right. after deleting `)` it's working fine. Strangely with extra bracket it works with vanilla graphite. 

Results returned by query are matching with vanilla graphite response. 

With sortby function still results are not accurate. User returned by following query with clickhouse is not not even the top 20 list of users. 

~~~
curl "http://<clickhouse>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.read.bytes_out,1),'last',true),1),4)&format=json&from=-5mins" | python -m json.tool
~~~

**Comment by Felixoid** [comment] 2021-03-22 20:33
I've tested it on our setup, and it seems that only `sortBy(*, 'avg')` is broken. All other functions work correctly.

**Comment by Felixoid** [comment] 2021-03-23 00:03
@ervikrant06 can you test the branch in #587 if it fixes your issue? It should fix most of the issues with sortBy?

**Comment by ervikrant06** [comment] 2021-03-23 06:53
thanks. Created new docker image using your PR. Still the issue seems to be present. 

Found one more difference following query with two `*` doesn't result anything. 

~~~
# curl "http://<VANILLA GRAPHITE>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.*.bytes_out,1),'last',true),1),4)&format=json&from=-5mins"

[{"target": "test1", "tags": {"name": "isilon.prod.isilon1.userstats.test1.read.bytes_out"}, "datapoints": [[12847030272.0, 1616481120], [15192518656.0, 1616481180], [15051862016.0, 1616481240], [15547779072.0, 1616481300], [15429808128.0, 1616481360]]}]

# curl "http://<CLICKHOUSE>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.*.bytes_out,1),'last',true),1),4)&format=json&from=-5mins"
[]
~~~

however following query returns the result: 

~~~
# curl "http://<CLICKHOUSE IP>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.read.bytes_out,1),'last',true),1),4)&format=json&from=-5mins"
~~~

**Comment by Felixoid** [comment] 2021-03-23 07:34
Just to clarify, I'd like to have the least target that causing the issue, which is still present. There are many targets mentioned and locally I can't reproduce the sortBy issue anymore.

**Comment by ervikrant06** [comment] 2021-03-24 08:11
If I am not mistaken you asked for the query still showing the issue, if yes, then following query still showing the issue:

~~~
curl "http://<CLICKHOUSE IP>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.read.bytes_out,1),'last',true),1),4)&format=json&from=-5mins"
~~~

**Comment by ervikrant06** [comment] 2021-03-24 08:30
Earlier I was using last function, I have tried average, yes results are not aligned with graphite-web output. 

~~~
curl "http://<CLICKHOUSE IP>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.read.bytes_out,1),'average',true),1),4)&format=json&from=-5mins"
~~~

Let's say user is doing multiple operations like read, write, link, delete, unlink on storage  and I want to do the average across all operations. 

First query will not work with clouhouse setup but same query return the results with graphite-web. Two wildcard `*` are not working fine with average query. 

~~~
curl "http://<CLICKHOUSE IP>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.*.bytes_out,1),'average',true),1),4)&format=json&from=-5mins"

curl "http://<GRAPHITE WEB>/render/?target=aliasByNode(limit(sortBy(keepLastValue(isilon.prod.isilon1.userstats.*.*.bytes_out,1),'average',true),1),4)&format=json&from=-5mins"
~~~

**Comment by Felixoid** [comment] 2021-03-24 11:56
- Does `'http://<CLICKHOUSE IP>/render/?target=isilon.prod.isilon1.userstats.*.*.bytes_out&format=json&from=-5mins'` work? If yes, what's the minimal set of functions to reproduce the issue?
- I can't reproduce the issue with the command `curl localhost:8080/render -d "target=limit(sortBy(keepLastValue(servers.*_admin.software.grafsy.carbon*.*),'average',true),4)&from=-5min&until=now&format=json"`, the output looks very legit to me.

**Comment by ervikrant06** [comment] 2021-03-26 06:46
> * Does `'http://<CLICKHOUSE IP>/render/?target=isilon.prod.isilon1.userstats.*.*.bytes_out&format=json&from=-5mins'` work? If yes, what's the minimal set of functions to reproduce the issue?

This doesn't work. it returns empty list. But it does return results with vanilla graphite setup. 

If I change the query to `"http://<CLICKHOUSE IP>/render/?target=isilon.prod.isilon1.userstats.*.read.bytes_out&format=json&from=-5mins"`  it does return the results. 



average function for me seems to be working as expected. Instead of average If I was using last then results are different from vanila graphite. I am good to use average for now.

**Comment by Felixoid** [comment] 2021-03-26 06:52
It sounds like graphite-clickhouse bug and out of the issue scope.

So let's focus on sortBy issue. Are you sure you run the version from PR?

**Comment by ervikrant06** [comment] 2021-03-26 08:00
Yes I am sure using new code. I have used following commands to create docker image and confirmed your changes before creating the docker image 
~~~
git clone https://github.com/go-graphite/carbonapi.git
git fetch origin pull/587/head
git checkout FETCH_HEAD
docker build -t carbonapi:PR .
~~~

sortBy function with `Average` is working fine. sortBy function with `Last` was not working as expected however after using transformNull I am getting expected results with last also. 

~~~
curl "http://<CLIKHOUSE IP>/render/?target=limit(sortBy(transformNull(condor.prod.pool1.usage.*),'last',true),1)&format=json&from=-15mins"   | python -m json.tool
~~~


I know in this case we want to focus on sortBy function but some flaw is present in groupByNode function as well. 

Unfortunately in this case I can't break the query into pieces as I need to all functions to see the results. 

~~~
curl "http://<CLICKHOUSE IP>/render/?target=limit(sortBy(groupByNode(condor.prod.*.requested_cpus.*,4,'sum'),'average',true),1)&format=json&from=-15mins"   | python -m json.tool
~~~

Above is returning me a user with values of 20K+ 

Since I know the user name from previous query hence if I run the next query specifically using user and doing the sum using `2` place instead of `4` from previous query output is 5k (expected one)

~~~
# curl "http://<CLICKHOUSE IP>/render/?target=limit(sortBy(groupByNode(condor.prod.*.requested_cpus.testuser1,2,'sum'),'average',true),1)&format=json&from=-15mins"   | python -m json.tool
~~~

In case of vanila graphite with first query itself I am getting right output of 5k

**Comment by Felixoid** [comment] 2021-03-26 10:49
> sortBy function with Average is working fine. sortBy function with Last was not working as expected however after using transformNull I am getting expected results with last also.

It is expected. Quite often the latest value in the series is Null, so w/o `keepLastValue` or `transformNull` you will get the NaN out of the aggregating with `sortBy`.

> Since I know the user name from previous query hence if I run the next query specifically using user and doing the sum using 2 place instead of 4 from previous query output is 5k (expected one)

Are you sure, you don't mean to use `groupByNodes(condor.prod.*.requested_cpus.*,'sum',2,4)`? Because I have a feeling like you want to group by few nodes

**Comment by ervikrant06** [comment] 2021-03-26 11:39
yes i have to use `groupByNode` not `groupbynodes`. 

Reason: I am using limit with value of one to get the top user with max number of requested_cpus across all prod hpc pools. If I use groupByNodes summing over 2,4 it will give me results like following without limit option.:

~~~
curl "http://<CLICKHOUSE>/render/?target=sortBy(groupByNodes(condor.prod.*.requested_cpus.*,'sum',2,4),'average',true)&format=json&from=-15mins"   | python -m json.tool | grep 'name'

"condor.prod.pool1.requested_cpus.testuser1"
"condor.prod.pool2.requested_cpus.testuser1"
"condor.prod.pool3.requested_cpus.testuser1"
"condor.prod.pool4.requested_cpus.testuser1"
"condor.prod.pool1.requested_cpus.testuser2"
"condor.prod.pool2.requested_cpus.testuser2"
"condor.prod.pool3.requested_cpus.testuser2"
"condor.prod.pool4.requested_cpus.testuser2"
~~

Now adding limit of 1 will give me the result of user from one pool not aggregated from all pools. 

~~~
 curl "http://<CLICKHOUSE>/render/?target=limit(sortBy(groupByNodes(condor.prod.*.requested_cpus.*,'sum',2,4),'average',true),1)&format=json&from=-15mins"   | python -m json.tool | grep 'name'
~~~

But if I use groupbyNode on 4 field then it give me total requested_cpus value for a user from all pools. Putting limit of 1 give me the top user aggregating requested_cpus from all present pools (2nd field).

**Comment by Felixoid** [comment] 2021-03-26 11:48
Then you check is not valid. Instead of comparing `groupByNode(condor.prod.*.requested_cpus.*,4,'sum')` with `groupByNode(condor.prod.*.requested_cpus.testuser1,2,'sum')` I would expect comparing with `sum(condor.prod.*.requested_cpus.testuser1)`. See description https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.groupByNode

**Closed** 2021-03-26 22:22 UTC
Labels: bug
