### ISSUE TITLE
asPercent seems to misbehave

### ISSUE THREAD

**Issue by grobian** [go-graphite/carbonapi#115] opened 2016-03-09 10:21 UTC
http://graphite.readthedocs.org/en/latest/functions.html#graphite.render.functions.asPercent

When used with two metrics and no value to determine the 100%, carbonapi draws a 100% value, graphite-web draws two lines with the corresponding percentage calculations based on the sum of both.

**Comment by dgryski** [comment] 2016-08-15 12:34
I can't reproduce this.

**Comment by dgryski** [comment] 2016-09-07 14:19
I have a failing test case now.

**Comment by Civil** [comment] 2017-04-26 07:44
Can you please share the test case?

**Comment by Civil** [comment] 2022-12-06 00:21
It looks bug is extremely old and since then asPercent received a bunch of bug fixes, so closing that.

**Closed by Civil** 2022-12-06 00:21 UTC
Labels: bug, graphite-web compatibility
